Reduce vector to scalar
JetBrains-Research/spla pull request #107
Opened 2021-12-21 15:44 UTC by Glebanister

2021-12-22 12:26 UTC, EgorOrachyov requested changes

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/algo/SplaAlgorithmParams.hpp
> +        RefPtr<Type> ts;
При редуцировании, вектор и скаляр должны иметь один тип t, а reduce `f: t x t -> t`, поэтому достаточно только одного поля t.

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        }
Здесь создается сразу набор из N скаляров, но - некоторые блоки вектора могут быть пустыми, => при редуцировании они ничего не вернут и их не надо сохранять.

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +            SPDLOG_LOGGER_TRACE(logger, "Reduce block i={} nnz={}", i, params.v->GetNvals());
1. param.s - это out параметр. Если блок пустой, то там будет null.
2. Если блок не пустой, результат редуцирования не null
3. Если результат редуцирования не null, то его надо добавить (push) в intermediate buffer

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        }
А если их 0 - т.е нужна еще проверка, если их 0, то argS->RemoveValue(). И результат - это пустой скаляр

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/algo/vector/SplaVectorReduceCOO.cpp
> +    p->s->GetStorage()->SetValue(ScalarValue::Make(std::move(reduced)));
Тип p->s должен быть ScalarValue

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/algo/SplaAlgorithmParams.hpp
> +        RefPtr<Scalar> s;
Тип s должен быть ScalarValue, а не Scalar. Этот ScalarValue out параметр.

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        params.s = argS;
params.s не надо ставить, это out параметр.

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        SPDLOG_LOGGER_TRACE(logger, "Final reduce of intermediate buffer, nnz={}", nnzIntermediate);
После выполнения, надо сделать s->SetValue(params.s)

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/algo/vector/SplaVectorReduceCOO.cpp
> +    compute::vector<unsigned char> reduced = Reduce(vector->GetVals(), valueByteSize, reduceOp->GetSource(), queue);
Если блок пустой, то надо проверить это и return сделать.
В таком случает p->s трогать не надо, он останется null

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/storage/SplaScalarValue.cpp
> +
У ScalarValue Value иммутабельный! Его нельзя менять, тк к нему на чтение доступ из разных потоков может быть. Поэтому надо убрать этот метод.

2021-12-22 12:26 UTC, EgorOrachyov commented on sources/storage/SplaScalarValue.hpp
> +        [[nodiscard]] Value &GetVal() noexcept;
Убрать

2021-12-22 12:26 UTC, EgorOrachyov commented on tests/TestVectorReduce.cpp
> +#include <storage/SplaScalarValue.hpp>
Это запрещено. Внутренности библиотеки (кроме compute тестов) нельзя инклудить в тесты

2021-12-22 12:26 UTC, EgorOrachyov commented on tests/TestVectorReduce.cpp
> +    auto &reducedActual = spS->GetStorage()->GetValue()->GetVal();
Так нельзя делать. Чтобы получить доступ к значению скаляра, надо использовать Expression NodeReadData для скаляра (см TestDataScalar). Из-за этого как раз и не компилируется на CI, тк все что связано со ScalarStorage и тд - это приватные символы, они не экспортируются из .dll файла. Надо удалить `spS->GetStorage()->GetValue()->GetVal();` и использовать честный ReadData expression.

2021-12-22 12:26 UTC, EgorOrachyov commented on tests/utils/Vector.hpp
> +            }
Пустые контейнеры нельзя редуцировать, поэтому тут exception должен быть.
Или на крайний случай `return T();`, а не `return 0;`

2021-12-22 12:26 UTC, EgorOrachyov commented on tests/utils/Values.hpp
> +    }
Выглядит как франкенштейн. У скаляров на CPU стороне есть вполне конкретные типы, для их сравнения можно просто использовать EqWithError(a, b)

2021-12-22 12:26 UTC, EgorOrachyov commented on tests/TestVectorReduce.cpp
> +    std::memcpy(bytesExpected.data(), &reducedExpected, sizeof(reducedExpected));
Это убрать, см TestDataScalar

2021-12-23 13:02 UTC, EgorOrachyov requested changes

2021-12-23 13:02 UTC, EgorOrachyov commented on sources/algo/vector/SplaVectorReduceCOO.cpp
> +        p->scalar = nullptr;
У структуры Params все указатели инициализируются null по умолчанию, 
т.е. явно не надо  присваивать null для out параметра.

2021-12-23 13:02 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        }
В начало процедуры просто добавить
if (!argV->GetStorage()->GetNvals()) {
  argS->GetStorage()->RemoveValue();
  return;
}

2021-12-23 13:29 UTC, EgorOrachyov commented on sources/expression/vector/SplaVectorReduce.cpp
> +        library->GetAlgoManager()->Dispatch(Algorithm::Type::VectorReduce, params);
По идее, тут тогда нужен явный finish, перед вызовом Dispatch

2021-12-23 13:38 UTC, Glebanister commented on sources/algo/vector/SplaVectorReduceCOO.cpp
> +        p->scalar = nullptr;
Мне кажется это поможет избежать случайных ошибок, плюс выглядит очень читаемо: нет значений - scalar = null

2021-12-24 09:55 UTC, merged