Implement ReduceScalar & ScalarEWiseAdd
JetBrains-Research/spla pull request #113
Opened 2021-12-30 16:33 UTC by Glebanister

2021-12-31 08:41 UTC, EgorOrachyov requested changes

2021-12-31 08:41 UTC, EgorOrachyov commented on include/spla-cpp/SplaExpressionNode.hpp
> +                case ExpressionNode::Operation::ScalarEWiseAdd:
А default куда делся

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/SplaExpression.cpp
> +    }
См примеры выше CHECK_RAISE_ERROR(!accum.IsNull || accum->CanApply(....), ...)

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/algo/SplaAlgorithm.hpp
> +                case Algorithm::Type::VectorReduce:
default куда делся

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/algo/SplaAlgorithmParams.hpp
> +        RefPtr<MatrixBlock> matrix;   // matrix block to reduce of type t
По соглашению, должно быть ParamsMatrixReduceScalar

![image](https://user-images.githubusercontent.com/31863304/147811863-51497755-a65c-457e-a33c-e839a2002d3c.png)

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/algo/matrix/SplaReduceScalarCOO.cpp
> +bool spla::ReduceScalarCOO::Select(const spla::AlgorithmParams &params) const {
MatrixReduceScalarCOO, см соглашение имен для похожих алгоритмов в этой же папке, префикс `Matrix`

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/algo/matrix/SplaReduceScalarCOO.hpp
> +    class ReduceScalarCOO : public Algorithm {
MatrixReduceScalarCOO, см соглашение имен для похожих алгоритмов в этой же папке, префикс `Matrix`

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/algo/matrix/SplaReduceScalarCOO.hpp
> +    class ReduceScalarCOO : public Algorithm {
MatrixReduceScalarCOO **final** :  .....

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/SplaExpressionManager.cpp
> +    Register(new ReduceScalar());
MatrixReduceScalar, см соглашение имен для похожих алгоритмов для матриц, префикс `Matrix`

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/matrix/SplaReduceScalar.cpp
> +bool spla::ReduceScalar::Select(std::size_t nodeIdx, const spla::Expression &expression) {
MatrixReduceScalar, см соглашение имен для похожих алгоритмов для матриц, префикс `Matrix`

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/matrix/SplaReduceScalar.cpp
> +        }
если есть accum, то просто так remove value нельзя делать. значение должно остаться

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/matrix/SplaReduceScalar.cpp
> +
В случае, если пользователь хочет аккумулировать результат, проверка другая.
1. если у дескриптора есть флаг AccumResult, тогда accum должен быть !null (иначе ошибка). Аккумулируем резульат
2. если AccumResult нет у дескриптора, тогда не делаем аккумулирование (в этом случае аргумент accum dont care)

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/matrix/SplaReduceScalar.hpp
> +    class ReduceScalar final : public NodeProcessor {
MatrixReduceScalar

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/expression/scalar/SplaScalarEWiseAdd.cpp
> +    builder.Emplace([=]() {
Здесь не нужен билдер, тк всего одна задача, ее можно делать прямо здесь, внутри process

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/utils/SplaIgnore.hpp
> +#endif//SPLA_SPLAIGNORE_HPP
Это что и зачем?

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/utils/SplaScalarBuffer.cpp
> +    return ::spla::Reduce2(buffer, valueByteSize, reduce->GetSource(), queue);
это ведь итак в spla namespace, просто return Reduce2

2021-12-31 08:41 UTC, EgorOrachyov commented on sources/utils/SplaScalarBuffer.hpp
> +        std::deque<RefPtr<ScalarValue>> mScalars;
Если элементы только добавляются, почему не std::vector

2021-12-31 08:41 UTC, EgorOrachyov commented on tests/TestReduceScalar.cpp
> +/**********************************************************************************/
TestMatrixReduceScalar

2021-12-31 08:41 UTC, EgorOrachyov commented on tests/TestReduceScalar.cpp
> +                      const std::optional<std::pair<spla::RefPtr<spla::FunctionBinary>, std::function<Type(Type, Type)>>> &spApply,
Зачем такой огород, еще чуть-чуть и нечитаемо вовсе.
Если у тестов уже выработался некий "единый стиль" написания, то ему надо следовать, иначе велкам рефакторить остальные 18 файлов с тестами

2021-12-31 08:41 UTC, EgorOrachyov commented on tests/TestScalarEWiseAdd.cpp
> +    //    testLocal(std::numeric_limits<std::uint32_t>::max(), 0);
Если закомментировано, то удалить

2022-01-02 12:43 UTC, Glebanister commented on include/spla-cpp/SplaExpressionNode.hpp
> +                case ExpressionNode::Operation::ScalarEWiseAdd:
Если мы не разобрали какой-то случай case у enum, то мы, мне кажется, должны видеть сообщение об ошибке, или хотя бы ворнинг

2022-01-02 12:56 UTC, Glebanister commented on include/spla-cpp/SplaExpressionNode.hpp
> +                case ExpressionNode::Operation::ScalarEWiseAdd:
Может в конце лучше кинуть исключение?

2022-01-02 13:05 UTC, Glebanister commented on sources/utils/SplaIgnore.hpp
> +#endif//SPLA_SPLAIGNORE_HPP
Это удалю. Я в какой-то момент хотел избавиться от всех ворнингов, но понял, что их больше всего в бусте. Может добавить флаг, который будет подавлять предупреждения о неиспользуемой переменной? Потому что в них часто какая-то полезная информация содержится, котороая потенциально может избавить нас от ошибки. А сейчас предупреждений очень много, среди них сложно вычленить полезные

2022-01-11 11:35 UTC, EgorOrachyov approved these changes

2022-01-11 11:35 UTC, merged