Implement GPU version of MergeByKey
JetBrains-Research/spla pull request #74
Opened 2021-11-04 21:18 UTC by Glebanister

2021-11-04 21:29 UTC, Glebanister commented
Issue #64 should also be closed with this PR

2021-11-05 14:41 UTC, EgorOrachyov requested changes

2021-11-05 14:41 UTC, EgorOrachyov commented on tests/TestMergeByKey.cpp
> +}
Remove Shallow test or add actual cpu-merge test

2021-11-06 12:16 UTC, EgorOrachyov approved these changes

2021-11-06 12:16 UTC, merged