Implement MxM COO
JetBrains-Research/spla pull request #88
Opened 2021-11-26 13:55 UTC by Glebanister

2021-11-26 14:12 UTC, EgorOrachyov commented on tests/TestMxM.cpp
> +
Seems redundant

2021-11-26 14:25 UTC, EgorOrachyov commented on sources/algo/mxm/SplaMxMCOO.cpp
> +        wVals.resize(NNZ * wValueByteSize, queue);
Result vectors automatically resized inside our reduce function

2021-11-26 14:26 UTC, EgorOrachyov commented on sources/algo/mxm/SplaMxMCOO.cpp
> +    }
We do not create blocks without values. So, block either null, or nnz > 0

2021-11-26 14:27 UTC, EgorOrachyov commented on sources/algo/mxm/SplaMxMCOO.cpp
> +    compute::vector<unsigned int> wTmpCols(ctx);
compute::vector<unsigned int> wTmpRows(ctx), wTmpCols(ctx);

2021-11-29 15:04 UTC, EgorOrachyov commented on sources/algo/mxm/SplaMxMCOO.cpp
> +    }
segmentLengths.(a.GetNvals() + 1)
...
exclusive_scan(segmentLengths.begin(), segmentLengths.end(), outputPtr.begin(), ...);
// outputPtr.end() == nnz

2021-12-07 15:44 UTC, EgorOrachyov requested changes

2021-12-07 15:44 UTC, EgorOrachyov commented on sources/algo/mxm/SplaMxMCOO.cpp
> +    auto &logger = library->GetLogger();
Стоит обратить внимание, и аккуратно учесть complement flag как в [vxm](https://github.com/JetBrains-Research/spla/blob/033c4cbcea788160cf6db4a151b3d1faa1282e85/sources/algo/vxm/SplaVxMCOO.cpp#L67) (строки 67 - 73)

| hasMask | complement | mask is null | what to do? |
| ---- | ---- | ---- | ---- | 
| false | - | - | no mask |
| true | false | null | return |
| true | false | not null | apply mask (as normal) |
| true | true | null | no mask (full result saved) |
| true | true | not null | apply mask (complement) |

2021-12-07 15:44 UTC, EgorOrachyov commented on tests/utils/Random.hpp
Может лучше [std::uniform_dist](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)

2021-12-07 15:59 UTC, EgorOrachyov commented on sources/algo/SplaAlgorithmParams.hpp
> +        enum class BlockSlicingMethod {
А зачем он? Вроде нигде не используется толком

2021-12-07 18:18 UTC, Glebanister commented on sources/algo/mxm/SplaMxMCOO.cpp
> +    auto &logger = library->GetLogger();
Добавил комментарии в коде, где какие случаи разбираются

2021-12-09 17:02 UTC, EgorOrachyov approved these changes

2021-12-09 17:02 UTC, merged